# Generated by Django 5.0.6 on 2024-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
