# Generated by Django 5.0.6 on 2024-07-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_task_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
